export const GET_CURRENT_APPOINTMENTS_SUCCESS = 'GET_CURRENT_APPOINTMENTS_SUCCESS';
export const ADD_APPOINTMENTS_SUCCESS = 'ADD_APPOINTMENTS_SUCCESS';
export const EDIT_APPOINTMENTS_SUCCESS = 'EDIT_APPOINTMENTS_SUCCESS';
export const DELETE_APPOINTMENTS_SUCCESS = 'DELETE_APPOINTMENTS_SUCCESS';
export const GET_PREVIOUS_APPOINTMENTS_SUCCESS = 'GET_PREVIOUS_APPOINTMENTS_SUCCESS';
