export default {
  SPLASH: 'SPLASH',
  SUBJECTS: 'SUBJECTS',
  STUDENTS: 'STUDENTS',
  STUDENTS_APPOINTMENTS: 'STUDENTS_APPOINTMENTS',
  LOGIN: 'LOGIN',
  HOME: 'HOME',
  PREVIOUS_APPOINTMENT: 'PREVIOUS_APPOINTMENT',
  NEXT_APPOINTMENT: 'NEXT_APPOINTMENT',
  SELECT_EXPERIMENT: 'SELECT_EXPERIMENT',
  SELECT_DATE: 'SELECT_DATE',
  CONFIRM_APPOINTMENT: 'CONFIRM_APPOINTMENT',
  APPOINTMENT_DETAIL: 'APPOINTMENT_DETAIL',
};
