export default {
  SPLASH: 'SPLASH',
  LOGIN: 'LOGIN',
  HOME: 'HOME',
  PREVIOUS_APPOINTMENT: 'PREVIOUS_APPOINTMENT',
  NEXT_APPOINTMENT: 'NEXT_APPOINTMENT',
  SELECT_EXPERIMENT: 'SELECT_EXPERIMENT',
  SELECT_DATE: 'SELECT_DATE',
  CONFIRM_APPOINTMENT: 'CONFIRM_APPOINTMENT',
};
